name: "Leila Geramian, CCC SLP - Home-based Speech & Language Therapy"
brand: Williamsburg Speech Therapy
description: "Home-based Speech & Language Therapy"
keyword: "speech therapy, speech language pathology, slp, brooklyn speech, williamsburg speech"
url: http://williamsburgspeechtherapy.com
year: 2015
author: Leila Geramian
email:
analytics:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
sass:
  compressed: true
  load_paths:
    - _sass
    - bower_components/foundation/scss

exclude:
  - node_modules
