# Site settings
title: "Leila Geramian, CCC SLP - Home-based Speech & Language Therapy"
email: leilag.SLP@gmail.com
description: "Home-based Speech & Language Therapy"
keyword: "speech therapy, speech language pathology, slp, brooklyn speech, williamsburg speech"
url: http://williamsburgspeechtherapy.com
year: "2015"
author: Leila Geramian
analytics:
  gtm: GTM-5LM88L
  # ga: UA-71856391-1
  fb_pixel: 171870166503294
  intercom: x7tqao7j
  olark: 4658-436-10-7095

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '#d2386f'
  links: '#d2386f'

# Social networks usernames (many more available: google-plus,
# flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/williamsburgslp
  - title: facebook
    url: https://facebook.com/williamsburgspeechtherapy

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty
sass:
  compressed: true
